spring:
  datasource:
    url: jdbc:mysql://202.196.37.91:3306/zut-communicate?useUnicode=true&characterEncoding=utf8
    username: zutlnp
    password: zutlnp
  jpa:
    database: MYSQL
    show-sql: true
  #Hibernate ddl auto (validate|create|create-drop|update)
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect